### PR TITLE
added Makefile.inc

### PR DESCRIPTION
**Pull request by steviestickman**

### CODE REVIEW

**Comment by LRstudentHU** [comment]
Datastructures is included through the internal communication module, which in turn is required by every non-native target.

**Comment by steviestickman** [comment]
i don't like it that this module that is actually small and could potentially be reused in non R2D2 projects, requires a different module to be used and build. not every test setup requires the entire internal communication module.

>which in turn is required by every non-native target.

where is that documented?

**Comment by steviestickman** [comment]
also, while building internal communication module would include the datastructures library. including the internal_communication/Makefile.inc does not include the header files of datastructures

**Comment by LRstudentHU** [comment]
It adds it in the makefile.inc, but your points are fair.
This library does not have a sources folder, could you remove that from the .inc?
Then I'll merge it in.

**Comment by steviestickman** [comment]
i think what should happen though is that the implementation and declarations of the data-structures should be separated in to headers and sources. that is however beyond the scope of this pull request so i will for now remove the folder from the makefile.inc

**Comment by LRstudentHU** [comment]
All structures are templated, no cpp files required.

**Pull request merged**
